/* eslint-disable max-len */
// As the whole page is generated by Markdown > HTML and reset on each change,
// we do not ever touch this. Thus, it's ok that styling rules are not
// considered strictly

import React from 'react';

export class Imprint extends React.Component {
  render() {
    return <div className={'min-h-screen bg-red-1 flex justify-center items-center'}>
      <div className={'w-4/5 mx-auto mt-40 p-8'}>
        <p><strong>Angaben gemäß § 5 TMG</strong></p>
        <p>Legallovestech</p>
        <p><strong>z. Hd. Sebastian Nagl</strong></p>
        <p>Prof-Huber-Platz 2</p>
        <p>80530 Muenchen</p>
        <p><strong>E-Mail: hallo@legallovestech.de</strong></p>
        <p><strong>Dieses Impressum gilt auch für unsere Social-Media-Präsenzen</strong></p>
        <p><strong>Bildernachweis</strong></p>
        <p><strong>Sofern nicht anderweitig gekennzeichnet verwendet diese Webseite eigene oder Public Domain Bilder. Eigene Bilder sind urheberrechtlich geschützt und dürfen nicht ohne unsere Zustimmung verwendet werden. Die Fotos alleine dürfen nicht herausgetrennt oder in irgendeiner Art verändert werden. Es ist immer der gesamte Text und Quellpfad abzubilden.</strong></p>
        <p><strong>High Five Lady -</strong> Foto von <strong><a href="https://www.pexels.com/de-de/@olia-danilevich?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">olia danilevich</a></strong> von <strong><a href="https://www.pexels.com/de-de/foto/menschen-frau-buro-geschaft-8145330/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong></p>
        <p>Library - Foto von <strong><a href="https://www.pexels.com/de-de/@element5?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Element5 Digital</a></strong> von <strong><a href="https://www.pexels.com/de-de/foto/selektiver-fokus-fotografie-des-bucherregals-mit-buchern-1370296/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong></p>
        <p>Lecture - Foto von <strong><a href="https://www.pexels.com/de-de/@mentatdgt-330508?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">mentatdgt</a></strong> von <strong><a href="https://www.pexels.com/de-de/foto/mann-im-anzug-jacke-neben-projektor-bildschirm-stehen-2173508/?utm_content=attributionCopyText&amp;utm_medium=referral&amp;utm_source=pexels">Pexels</a></strong></p>
        <p><strong>Verweise und Links</strong></p>
        <p><strong>Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</strong></p>
        <p><strong>Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</strong></p>
        <p><strong>Urheberrecht</strong></p>
        <p><strong>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</strong></p>
        <p><strong>Streitschlichtung</strong></p>
        <p><strong>Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: <a href="https://ec.europa.eu/consumers/odr">https://ec.europa.eu/consumers/odr</a>.Unsere E-Mail-Adresse finden Sie oben im Impressum. Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</strong></p>

      </div>
    </div>;
  }
}
